version: '3.9'

services:
  postgres-estudos:
    image: postgres:16
    container_name: ${POSTGRES_CONTAINER}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - pg_lab_data:/var/lib/postgresql/data
    networks:
      - estudos_net

  redis-estudos:
    image: redis:7
    container_name: ${REDIS_CONTAINER}
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_lab_data:/data
    networks:
      - estudos_net

volumes:
  pg_lab_data:
  redis_lab_data:

networks:
  estudos_net:
    driver: bridge
